# Generated by Django 6.0.1 on 2026-03-02 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nickname',
        ),
        migrations.CreateModel(
            name='CustomUserCreateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
