# Generated by Django 6.0.1 on 2026-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=5000, verbose_name='自己紹介'),
        ),
    ]
