# Generated by Django 6.0.1 on 2026-03-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcreatelog',
            old_name='created',
            new_name='created_at',
        ),
    ]
